### ISSUE TITLE
Allow a Cassandra database to be scaled down

### ISSUE THREAD

**Issue by wallrj** [jetstack/navigator#140]
/kind feature

Right now, if you scale down a Cassandra database, 
 * the Cassandra controller will immediately decrease the StatefulSet replica count,
 * the StatefulSet controller will delete the pods with the largest index.
 * If there is data which is only replicated on those pods, the data will be lost.

  * [x] #152 Create PilotResources.
  * [x] #141 Create a Cassandra Pilot and make it the entrypoint.
 *  [x] #161 RBAC policy to allow a pilot to list and update the status of Pilot resources
  * [ ] #169 have the pilot update the status of its PilotResource.
  * [ ] Only scale down the cluster when Pilot status shows that the Pilot has removed its database node from the cluster.

**Comment by wallrj** [comment]
Supplanted by #285
