### ISSUE TITLE
Pilot resource type tracking issue

### ISSUE THREAD

**Issue by munnerz** [jetstack/navigator#41]
This is a tracking issue for implementing the features described in #40.

The progress for this issue can be found in #39

---
* [x] genericpilot
  * [x] basic control loop watching Pilot resource
  * [x] leader elected control loop watching Pilot resource
    * [x] leader election package
  * [x] spawning subprocess
  * [x] support for periodics (functions that are executed every N seconds)
  * [x] health checks
  * [x] executing hooks on subprocess state change
    * [x] preStart
    * [x] postStart
    * [x] preStop
    * [x] postStop
---
* [ ] controller
  * [ ] update elasticsearch controller
    * [x] new CLI flags for pilot
    * [x] new Pilot fields need to be set
    * [ ] setting decommission phase on resources on scale down request
  * [ ] implement pilot controller
    * [ ] garbage collect old Pilot resources
    * [ ] automatically set Ready state to false after duration
---
* [x] apiserver
  * [x] new pilot types added (this can be a breaking change)
---
* [ ] pilot-elasticsearch
  * [x] starts elasticsearch process
  * [x] loads `elasticsearch.yml` from Pilot resource
  * [x] sets node roles appropriately
  * [x] updates Pilot status with actual status
  * [x] installing plugins
  * [ ] leader elected decommission handler

**Comment by munnerz** [comment]
The remaining points will be tracked in issues as the appropriate functionality is added again, since the Actions changes have happened.
